/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

/**
 * All available building types in the kingdom.
 */
export enum BuildingType {
  None = 'None',
  Path = 'Path',
  Hovel = 'Hovel',
  Market = 'Market',
  Farm = 'Farm',
  Keep = 'Keep',
  // Military
  Barracks = 'Barracks',
  Wall = 'Wall',
  Gatehouse = 'Gatehouse',
  Tower = 'Tower',
  Moat = 'Moat',
  Drawbridge = 'Drawbridge',
}

/**
 * Configuration for a specific building type.
 */
export interface BuildingConfig {
  type: BuildingType;
  cost: number;
  name: string;
  description: string;
  color: string; // UI Color representation
  popGen: number; // Subjects generated per game tick
  incomeGen: number; // Gold generated per game tick
  defense?: number; // Defense rating contribution
}

/**
 * State of a single tile on the game grid.
 */
export interface TileData {
  x: number;
  y: number;
  buildingType: BuildingType;
  variant?: number;
  rotation?: number; // 0, 1, 2, 3 corresponding to 90deg increments
  isOpen?: boolean; // Toggle state for gates/bridges
  isLocked?: boolean; // Security state for gates/bridges
  isWet?: boolean; // Hydration state for moats
  level: number; // Building level (1-3)
}

/**
 * The 2D grid structure representing the kingdom.
 */
export type Grid = TileData[][];

export enum Season {
  Spring = 'Spring',
  Summer = 'Summer',
  Autumn = 'Autumn',
  Winter = 'Winter'
}

/**
 * Global statistics for the kingdom's progress.
 */
export interface KingdomStats {
  gold: number;
  subjects: number;
  soldiers: number;
  officers: number;
  day: number;
  defense: number;
  happiness: number; // 0-100
  season: Season;
}

/**
 * AI Advisor Personas that influence goal generation.
 */
export enum AdvisorPersona {
  Balanced = 'The Steward',
  Warlord = 'The Warlord',
  Merchant = 'The Merchant',
  Builder = 'The Architect'
}

/**
 * A quest or objective provided by the AI Advisor.
 */
export interface AIGoal {
  description: string;
  targetType: 'subjects' | 'gold' | 'building_count' | 'defense' | 'soldiers';
  targetValue: number;
  buildingType?: BuildingType; 
  reward: number;
  completed: boolean;
}

/**
 * A choice within a game event.
 */
export interface EventChoice {
  text: string;
  costGold?: number;
  effect?: (stats: KingdomStats) => KingdomStats;
  outcomeText: string;
}

/**
 * A dynamic event generated by the AI or system.
 */
export interface GameEvent {
  id: string;
  title: string;
  description: string;
  choices: EventChoice[];
}

/**
 * An announcement displayed in the news feed.
 */
export interface NewsItem {
  id: string;
  text: string;
  type: 'positive' | 'negative' | 'neutral';
}

/**
 * Chat message for the Advisor interface.
 */
export interface ChatMessage {
  role: 'user' | 'advisor';
  text: string;
}

/**
 * Floating text for visual feedback.
 */
export interface FloatingText {
  id: string;
  x: number;
  y: number;
  text: string;
  color: string;
  life: number; // 0-1 for opacity
}

/**
 * Structure for local storage persistence.
 */
export interface SaveData {
  grid: Grid;
  stats: KingdomStats;
  persona: AdvisorPersona;
  version: number;
}
